#include <stdio.h>
#include<stdlib.h>
#include "ir.h"
#include "ast.h"
#include "codegen.h"

/* yyparse is generated by yacc */
int yyparse(void);

/* root comes from parser.y */
extern astnode *root;
/* ir_head from the ir.h file */
extern IRInstruction *ir_head;
int main(void) {
    if (yyparse() == 0) {
        printf("Parsing successful!\n");
        //print_ast(root, 0);
	generate_ir(root);
	//printf("--------Intermidiate Representation:----------\n");
	//print_ir();
	generate_code(ir_head);
    } else {
        printf("Parsing failed.\n");
    }
    return 0;
}

